import InviteText from '@/components/invite-text'
import Head from 'next/head'
import Image from 'next/image'
import styles from "../styles/styles.module.scss"
import { useEffect, useState } from 'react'
import ConfirmName from '@/components/confirm-name'
import HasConfirm from '@/components/has-confirm'

export default function Home() {

  const [confirm, setConfirm] = useState<boolean>(false)

  const [hasConfirm, setHasConfirm] = useState<boolean>(false)
  const [username, serUsername] = useState<string>("")

  const addValues = ({
    hash = "", name = ""
  }) => {
    localStorage.setItem("name", name)
    localStorage.setItem("hash", hash)

    setHasConfirm(true)
  }
  useEffect(() => {

    const getName = localStorage.getItem("name")
    const getHash = localStorage.getItem("hash")

    setHasConfirm(!!getName && !!getHash)

    !!getName && !!getHash && (serUsername(getName))

  }, [])



  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >

        <section>
          {hasConfirm ?
            (<HasConfirm name={username} />) :
            !confirm
              ? (<InviteText onConfirm={() => { setConfirm(true) }} />)
              : (<ConfirmName onConfirm={nome => { addValues(nome) }} />)

          }
        </section>

        <div className={styles.happyImage} >
          <Image width={300} height={300} loading="lazy" src={"/images/happy.jpg"} alt="imagem de aniversario"></Image>
        </div>

      </main>
    </>
  )
}
